# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Picsum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Picsum

	pod 'Kingfisher'

  target 'PicsumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PicsumUITests' do
    # Pods for testing
  end

end
